feat: added Shift endpoint and Shift interface
hack4impact-calpoly/general-vms pull request #31
Opened 2022-02-04 10:49 UTC by Pandoyer

issue #11,  I added placeholders for the 'Database' abstract class and the 'isUserAdmin' middleware function. The implementation was pretty much just to make the linter happy. 'shift-api' and 'shift-interface' are the real features.

2022-02-05 21:22 UTC, bglossner requested changes

2022-02-05 21:22 UTC, bglossner commented on test-app/backend/src/shift/shift-api.ts
> +  const { start, end, maxVolunteers, title, description, eventAdmin } = req.body as shift;
The start and end dates here are actually going to be given as numbers, not `Date`s. We just need to convert those numbers to dates after confirming the type. Perhaps a function called like `shiftPreProcessor` that takes a `Partial<Shift>` and goes through and converts the numbers to actual dates and returns the edited shift.

2022-02-05 21:22 UTC, bglossner commented on test-app/backend/src/shift/shift-api.ts
> +  console.log('POST: Creating Calendar Event...');
Nit: Creating Shift

2022-02-05 21:22 UTC, bglossner commented on test-app/backend/src/shift/shift-interface.ts
> +  description: string,
If this is optional, we should put a `?` after it, like `description?: string`

2022-02-05 21:22 UTC, bglossner commented on test-app/backend/src/shift/shift-api.ts
> +import app from '../server';
One thing I notice here is that while you are doing good error checking, there are still some assumptions. For the start/end dates for instance, you check if `start >= end`. But what if `start` or `end` is actually not even defined. We also need checks for that sort of thing, like with what you did for title. `if (!start || !end || start >= end) <some_error>`. There are other places that need this checked too.

2022-02-05 21:23 UTC, bglossner commented
Also, sorry one more comment: make sure to write some unit tests!

2022-02-05 21:23 UTC, bglossner commented
Glad to see a PR out for this. Good first iteration on the task!

2022-02-19 17:51 UTC, Pandoyer commented
@bglossner got the tests to work with the express router. I have omitted the isUserAdmin middleware function because the tests are required to pass for a commit.

2022-02-20 19:27 UTC, bglossner requested changes

2022-02-20 19:27 UTC, bglossner commented on test-app/backend/test/models/shift/shift-api.test.ts
> +test('POST  /api/new-shift', async () => {
Can you split each `await request(app)` into a new test?

The test description should be like `POST /api/new-shift; Shift fails to create due to bad no title provided`

2022-02-20 19:27 UTC, bglossner commented on test-app/backend/src/shift/shift-interface.ts
> +  getShiftTime(): number
Checking in here again on what the `getShiftTime` does. I don't see it called anywhere.

2022-02-22 10:55 UTC, Pandoyer commented on test-app/backend/src/shift/shift-interface.ts
> +  getShiftTime(): number
It was part of the original issue but you're right it doesn't do anything right now

2022-02-22 10:56 UTC, Pandoyer commented
@bglossner split up the tests and did without the getShiftTime() function

2022-02-22 18:44 UTC, bglossner requested changes

2022-02-22 18:44 UTC, bglossner commented on test-app/backend/test/models/shift/shift-api.test.ts
> +test('POST  /api/new-shift; Shift fails to create ecasue there is no title', async () => {
Misspelling here.

2022-02-22 18:44 UTC, bglossner commented on test-app/backend/test/models/shift/shift-api.test.ts
> +test('POST  /api/new-shift; Shift fails becasuse max volunteers is 0', async () => {
Misspelling here.

2022-02-22 20:37 UTC, bglossner approved these changes

2022-02-22 20:37 UTC, merged